version: "3.8"

services:
  postgres:
    container_name: postgres
    image: "postgres:14.1-alpine"
    environment:
      - POSTGRES_DB=portfolio
      - POSTGRES_USER=heidless
      - POSTGRES_PASSWORD=havana11
      - POSTGRES_HOST=postgres
  backend:
    container_name: backend
    build:
      context: ./backend
    env_file:
      - ./.env
    environment:
      - DEBUG=1
    ports:
      - ${PORT}:${PORT}
    expose:
      - ${PORT}
    volumes:
      - ./backend:/backend
    depends_on:
      - postgres
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/frontend/src